version: "3.7"
services:
  rabbitmq:
    container_name: aria-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  python-srv-api:
    container_name: aria-python-srv-app
    build:
      context: ./aria-srv-api
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes: 
      - "./aria-srv-api/:/app"
    networks:
      - backend
  python-ml-api:
    container_name: aria-python-ml-app
    build:
      context: ./aria-ml-api
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes: 
      - "./aria-ml-api/:/app"
      - "./aria-ml-api/naive_bayes.joblib:/app/naive_bayes.joblib"
    networks:
      - backend
networks:
  frontend:
    name: aria-frontend
    driver: bridge
  backend:
    name: aria-backend
    driver: bridge
