version: "3.7"
services:
  rabbitmq:
    container_name: aira-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  python-srv-api:
    container_name: aira-python-srv-app
    build:
      context: ./aira-srv-api
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes: 
      - "./aira-srv-api/:/app"
    networks:
      - backend
  python-ml-api:
    container_name: aira-python-ml-app
    build:
      context: ./aira-ml-api
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes: 
      - "./aira-ml-api/:/app"
      - "./aira-ml-api/naive_bayes.joblib:/app/naive_bayes.joblib"
    networks:
      - backend
  python-info-consumer:
    container_name: aira-python-info-consumer
    build:
      context: ./aira-info-consumer
      dockerfile: Dockerfile
    volumes: 
      - "./aira-info-consumer/:/app"
      - "./aira-info-consumer/naive_bayes.joblib:/app/naive_bayes.joblib"
    networks:
      - backend
networks:
  frontend:
    name: aira-frontend
    driver: bridge
  backend:
    name: aira-backend
    driver: bridge
